#![no_main]

use libfuzzer_sys::fuzz_target;
use qsc::adversarial::binding_fuzz::{
    category_from_input, exercise_binding_fuzz_case, BindingFuzzCategory,
    NA0487_BINDING_FUZZ_HELPER_SCOPE_CONSUMED_OK, NA0487_HELPER_API_NO_SECRET_OUTPUT_OK,
    NA0487_HELPER_API_REAL_REJECT_PATHS_OK, NA0487_HELPER_API_TEST_FUZZ_ONLY_OK,
    NA0487_HELPER_API_VECTOR_TRACEABILITY_OK,
};

const _NA0487_FUZZ_A1_MUTATION_TARGET_OK: &str = "NA0487_FUZZ_A1_MUTATION_TARGET_OK";
const _NA0487_FUZZ_B1_MUTATION_TARGET_OK: &str = "NA0487_FUZZ_B1_MUTATION_TARGET_OK";
const _NA0487_FUZZ_A2_MUTATION_TARGET_OK: &str = "NA0487_FUZZ_A2_MUTATION_TARGET_OK";
const _NA0487_FUZZ_SUITE_CONFUSION_TARGET_OK: &str =
    "NA0487_FUZZ_SUITE_CONFUSION_TARGET_OK";
const _NA0487_FUZZ_REPLAY_TARGET_OK: &str = "NA0487_FUZZ_REPLAY_TARGET_OK";
const _NA0487_FUZZ_STALE_PUBLIC_RECORD_TARGET_OK: &str =
    "NA0487_FUZZ_STALE_PUBLIC_RECORD_TARGET_OK";
const _NA0487_FUZZ_VECTOR_MANIFEST_TRACEABILITY_OK: &str =
    "NA0487_FUZZ_VECTOR_MANIFEST_TRACEABILITY_OK";
const _NA0487_NO_SECRET_MATERIAL_IN_FUZZ_INPUTS_OK: &str =
    "NA0487_NO_SECRET_MATERIAL_IN_FUZZ_INPUTS_OK";
const _NA0487_NO_FUZZ_COMPLETE_CLAIM_OK: &str = "NA0487_NO_FUZZ_COMPLETE_CLAIM_OK";
const _NA0487_NO_VECTOR_COMPLETE_CLAIM_OK: &str = "NA0487_NO_VECTOR_COMPLETE_CLAIM_OK";
const _NA0487_NO_REPLAY_PROOF_CLAIM_OK: &str = "NA0487_NO_REPLAY_PROOF_CLAIM_OK";
const _NA0487_NO_DOWNGRADE_PROOF_CLAIM_OK: &str = "NA0487_NO_DOWNGRADE_PROOF_CLAIM_OK";

fuzz_target!(|data: &[u8]| {
    let _ = NA0487_BINDING_FUZZ_HELPER_SCOPE_CONSUMED_OK;
    let _ = NA0487_HELPER_API_TEST_FUZZ_ONLY_OK;
    let _ = NA0487_HELPER_API_NO_SECRET_OUTPUT_OK;
    let _ = NA0487_HELPER_API_REAL_REJECT_PATHS_OK;
    let _ = NA0487_HELPER_API_VECTOR_TRACEABILITY_OK;

    let category = if data.first().copied().unwrap_or(0) == 0xff {
        BindingFuzzCategory::VectorTraceability
    } else {
        category_from_input(data)
    };
    let _ = exercise_binding_fuzz_case(category, data.get(1..).unwrap_or_default());
});
